CREATE DATABASE TECHSPIRE;
USE TECHSPIRE;
CREATE TABLE STUDENT_INFO(
ID INT PRIMARY KEY,
NAME VARCHAR(30),
CLASS VARCHAR(20),
MARKS INT NOT NULL,
GENDER VARCHAR(10)
);
INSERT INTO STUDENT_INFO
(ID,NAME,CLASS,MARKS,GENDER)
VALUES
(1,"John Deo","Four",75,"Female"),
(2,"Max Ruin","Three",85,"Male"),
(3,"Arnold","Three",55,"Male"),
(4,"Krish Star","Four",60,"Female"),
(5,"Alex John","Four",55,"Male"),
(6,"John Mike","Four",60,"Female"),
(7,"My John Rob","Five",78,"Male"),
(8,"Asruid","Five",85,"Male"),
(9,"Tes Qry","Five",78,"Male"),
(10,"Big John","Four",55,"Female");
SELECT distinct CLASS FROM STUDENT_INFO;
SELECT * FROM STUDENT_INFO WHERE MARKS>60;
SELECT * FROM STUDENT_INFO WHERE GENDER="male";
SELECT * FROM STUDENT_INFO WHERE MARKS>80 AND GENDER="MALE";
SELECT * FROM STUDENT_INFO WHERE MARKS<80 OR GENDER="FEMALE";
SELECT * FROM STUDENT_INFO WHERE MARKS BETWEEN 75 AND 85;
SELECT * FROM STUDENT_INFO WHERE GENDER IN ("FEMALE");
SELECT * FROM STUDENT_INFO WHERE GENDER NOT IN ("FEMALE");
SELECT * FROM STUDENT_INFO WHERE MARKS>60 LIMIT 3;
SELECT * FROM STUDENT_INFO ORDER BY MARKS ASC;
SELECT * FROM STUDENT_INFO ORDER BY MARKS DESC LIMIT 3;
SELECT COUNT(MARKS) FROM STUDENT_INFO; 
SELECT AVG(MARKS) FROM STUDENT_INFO;
SELECT SUM(MARKS) FROM STUDENT_INFO;
SELECT MAX(MARKS) FROM STUDENT_INFO;
SELECT MIN(MARKS) FROM STUDENT_INFO;
SELECT CLASS, AVG(MARKS) FROM STUDENT_INFO GROUP BY CLASS;
